version: "3"
services:
  web:
    container_name: yjm_azure_web
    build:
      context: .
      dockerfile: dockerization/web/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8082:80
