parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  logger:
    alias: 'monolog.logger'
    public: true

  RedisCacheRegistry:
    class: Common\DataStorage\Redis
    public: true

  AzureServiceBusAuthenticationCache:
    class: App\AzureServiceBus\Core\AzureServiceBusAuthenticationCache
    public: true
    arguments:
      - '@RedisCacheRegistry'

  AzureServiceBusAuthenticator:
    class: App\AzureServiceBus\Core\AzureServiceBusAuthenticator
    public: true
    arguments:
      - '@AzureServiceBusAuthenticationCache'
      - '@logger'
      - '%azure_active_directory.clientId%'
      - '%azure_active_directory.tenantId%'
      - '%azure_active_directory.clientSecret%'
      - '%azure_service_bus.namespace%'

  EntityEventManager:
    class: App\AzureServiceBus\EntityEventManager
    public: true
    arguments:
      - '@AzureServiceBusAuthenticator'
      - '@logger'
      - '%azure_service_bus.dew_topic_name%'
      - '%azure_service_bus.dew_sender_queue_prefix%'

  UploadBase64Cache:
    class: App\AzureBlobStorage\Service\UploadBase64Cache
    public: true
    arguments:
      - '@RedisCacheRegistry'
      - 2400 # 40 minutes in seconds.

  BlobStorageAuthenticator:
    class: App\AzureBlobStorage\Service\BlobStorageAuthenticator
    public: true
    arguments:
      - '%azure_blob_storage.storageAccountName%'
      - '%azure_blob_storage.defaultEndpointProtocol%'
      - '@UploadBase64Cache'
      - '%azure_active_directory.clientId%'
      - '%azure_active_directory.tenantId%'
      - '%azure_active_directory.clientSecret%'

  BlobStorageManager:
    class: App\AzureBlobStorage\Service\BlobStorageManager
    public: true
    arguments:
      - '@BlobStorageAuthenticator'
      - '%azure_blob_storage.containerName%'
      - '@kernel'
      - '@logger'